# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [18]:
dataset=pd.read_csv('./iris.csv')
#x=dataset[:,0:-1]
x=dataset.iloc[:,0:-1]
y=dataset.iloc[:,4:5]

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_y = LabelEncoder()
y.iloc[:, 0] = labelencoder_y.fit_transform(y.iloc[:, 0])

onehotencoder=OneHotEncoder()
y= onehotencoder.fit_transform(y).toarray()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 0)
dataset.head()
print(y.shape)
print(x.shape)




(150, 3)
(150, 4)


E:\anaconda3\lib\site-packages\pandas\core\indexing.py:630: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value
E:\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [19]:
classifier=tf.keras.models.Sequential()
classifier.add(tf.keras.layers.Dense(128, activation="relu" , input_dim=4))

classifier.add(tf.keras.layers.Dense(256, activation="relu" ))


classifier.add(tf.keras.layers.Dense(3, activation='softmax'))

classifier.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 128)               640       
_________________________________________________________________
dense_7 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 771       
Total params: 34,435
Trainable params: 34,435
Non-trainable params: 0
_________________________________________________________________


### STEP 4 : Compilation Step 

In [20]:
classifier.compile('adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

### STEP 5 : Evaluation 

In [21]:
classifier.fit(x_train, y_train, epochs=20)

W1221 11:11:46.044538  2628 training.py:504] Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>


Train on 135 samples
Epoch 1/20
135/135 [==============================] - 1s 4ms/sample - loss: 0.9204 - accuracy: 0.5556
Epoch 2/20
135/135 [==============================] - 0s 189us/sample - loss: 0.7164 - accuracy: 0.7185
Epoch 3/20
135/135 [==============================] - 0s 118us/sample - loss: 0.5746 - accuracy: 0.8741
Epoch 4/20
135/135 [==============================] - 0s 118us/sample - loss: 0.4881 - accuracy: 0.7259
Epoch 5/20
135/135 [==============================] - 0s 237us/sample - loss: 0.4214 - accuracy: 0.8963
Epoch 6/20
135/135 [==============================] - 0s 208us/sample - loss: 0.3911 - accuracy: 0.9185
Epoch 7/20
135/135 [==============================] - ETA: 0s - loss: 0.4112 - accuracy: 0.96 - 0s 207us/sample - loss: 0.3360 - accuracy: 0.9111
Epoch 8/20
135/135 [==============================] - 0s 207us/sample - loss: 0.3031 - accuracy: 0.9630
Epoch 9/20
135/135 [==============================] - 0s 444us/sample - loss: 0.2748 - accuracy: 0.9704
Epo

### STEP 6 : Prediction 

In [22]:

y_pred=classifier.predict(x_test)
print(y_pred)

W1221 11:11:51.099782  2628 training.py:504] Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>


[[7.89019105e-05 3.28590274e-02 9.67062116e-01]
 [7.50827231e-03 9.49815571e-01 4.26761135e-02]
 [9.98224556e-01 1.77509594e-03 3.46591662e-07]
 [4.31355002e-05 1.05000764e-01 8.94956112e-01]
 [9.92616355e-01 7.37927714e-03 4.32676734e-06]
 [1.89113562e-05 1.70815904e-02 9.82899487e-01]
 [9.94951010e-01 5.04629826e-03 2.76690912e-06]
 [4.87743132e-03 9.43580806e-01 5.15417419e-02]
 [3.09490948e-03 9.18191135e-01 7.87139311e-02]
 [1.35273673e-02 9.60811496e-01 2.56611053e-02]
 [1.59132571e-04 1.27667367e-01 8.72173488e-01]
 [7.76478741e-03 9.49636698e-01 4.25985903e-02]
 [4.24969243e-03 8.63415360e-01 1.32334948e-01]
 [4.11118986e-03 8.91434014e-01 1.04454868e-01]
 [4.13926132e-03 8.13245893e-01 1.82614893e-01]]


In [16]:
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))
classifier.evaluate(x_test,y_pred)

E:\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
W1221 09:36:38.638471  2628 training.py:504] Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.43      1.00      0.60        13
           2       0.00      0.00      0.00         6

   micro avg       0.43      0.43      0.43        30
   macro avg       0.14      0.33      0.20        30
weighted avg       0.19      0.43      0.26        30

[[ 0 11  0]
 [ 0 13  0]
 [ 0  6  0]]
30/30 [==============================] - 0s 1ms/sample - loss: 0.8411 - accuracy: 1.0000


[0.8411428928375244, 1.0]